CREATE EXTENSION IF NOT EXISTS "pgcrypto";

   -- 50 USERS
   INSERT INTO users (user_id, username, email, created_at, updated_at) VALUES
   (gen_random_uuid(), 'swift_shadow', 'user1@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'silent_river', 'user2@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'crimson_peak', 'user3@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'midnight_sun', 'user4@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'iron_giant', 'user5@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'blue_horizon', 'user6@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'golden_dawn', 'user7@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'silver_mist', 'user8@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'onyx_knight', 'user9@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'emerald_isle', 'user10@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'ruby_rose', 'user11@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'sapphire_sky', 'user12@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'diamond_dust', 'user13@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'pearl_gates', 'user14@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'obsidian_fury', 'user15@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'granite_golem', 'user16@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'quartz_queen', 'user17@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'topaz_titan', 'user18@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'amethyst_angel', 'user19@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'jade_jester', 'user20@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'lapis_lord', 'user21@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'malachite_mage', 'user22@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'sunstone_saint', 'user23@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'moonstone_monk', 'user24@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'bloodstone_brute', 'user25@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'citrine_cleric', 'user26@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'agate_archer', 'user27@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'beryl_bard', 'user28@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'garnet_guard', 'user29@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'jasper_judge', 'user30@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'zircon_zealot', 'user31@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'spinel_scout', 'user32@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'tourmaline_thief', 'user33@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'peridot_paladin', 'user34@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'iolite_illusionist', 'user35@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'kunzite_king', 'user36@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'morganite_marshal', 'user37@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'heliodor_hermit', 'user38@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'goshenite_gunslinger', 'user39@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'hiddenite_hacker', 'user40@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'tanzanite_templar', 'user41@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'alexandrite_assassin', 'user42@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'chrysoberyl_champion', 'user43@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'demantoid_druid', 'user44@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'tsavorite_sorcerer', 'user45@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'spessartite_specter', 'user46@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'rhodolite_rogue', 'user47@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'pyrope_priest', 'user48@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'almandine_alchemist', 'user49@example.com', NOW(), NOW()),
   (gen_random_uuid(), 'hessonite_hunter', 'user50@example.com', NOW(), NOW());

   -- 50 TRUCKS
   INSERT INTO trucks (truck_id, model, created_at, updated_at) VALUES
   ('AB-123-CD', 'Volvo FH16', NOW(), NOW()), ('EF-456-GH', 'Scania R730', NOW(), NOW()), ('IJ-789-KL', 'Mercedes-Benz Actros', NOW(), NOW()),
   ('MN-101-OP', 'MAN TGX', NOW(), NOW()), ('QR-112-ST', 'DAF XF', NOW(), NOW()), ('UV-131-WX', 'Iveco Stralis', NOW(), NOW()),
   ('YZ-141-AB', 'Renault T', NOW(), NOW()), ('CD-151-EF', 'Ford F-MAX', NOW(), NOW()), ('GH-161-IJ', 'Kamaz 54901', NOW(), NOW()),
   ('KL-171-MN', 'JAC K7', NOW(), NOW()), ('OP-181-QR', 'Freightliner Cascadia', NOW(), NOW()), ('ST-191-UV', 'Kenworth W900', NOW(), NOW()),
   ('WX-202-YZ', 'Peterbilt 389', NOW(), NOW()), ('AB-212-CD', 'Mack Anthem', NOW(), NOW()), ('EF-222-GH', 'Western Star 49X', NOW(), NOW()),
   ('IJ-232-KL', 'International LT', NOW(), NOW()), ('MN-242-OP', 'Volvo VNL', NOW(), NOW()), ('QR-252-ST', 'Scania S-Series', NOW(), NOW()),
   ('UV-262-WX', 'Mercedes-Benz Arocs', NOW(), NOW()), ('YZ-272-AB', 'MAN TGS', NOW(), NOW()), ('CD-282-EF', 'DAF CF', NOW(), NOW()),
   ('GH-292-IJ', 'Iveco Trakker', NOW(), NOW()), ('KL-303-MN', 'Renault K', NOW(), NOW()), ('OP-313-QR', 'Ford Cargo', NOW(), NOW()),
   ('ST-323-UV', 'Kamaz 6520', NOW(), NOW()), ('WX-333-YZ', 'JAC Gallop', NOW(), NOW()), ('AB-343-CD', 'Freightliner M2', NOW(), NOW()),
   ('EF-353-GH', 'Kenworth T800', NOW(), NOW()), ('IJ-363-KL', 'Peterbilt 579', NOW(), NOW()), ('MN-373-OP', 'Mack Pinnacle', NOW(), NOW()),
   ('QR-383-ST', 'Western Star 47X', NOW(), NOW()), ('UV-393-WX', 'International HV', NOW(), NOW()), ('YZ-404-AB', 'Volvo FMX', NOW(), NOW()),
   ('CD-414-EF', 'Scania P-Series', NOW(), NOW()), ('GH-424-IJ', 'Mercedes-Benz Atego', NOW(), NOW()), ('KL-434-MN', 'MAN TGM', NOW(), NOW()),
   ('OP-444-QR', 'DAF LF', NOW(), NOW()), ('ST-454-UV', 'Iveco Eurocargo', NOW(), NOW()), ('WX-464-YZ', 'Renault D', NOW(), NOW()),
   ('AB-474-CD', 'Ford F-650', NOW(), NOW()), ('EF-484-GH', 'Kamaz 4308', NOW(), NOW()), ('IJ-494-KL', 'JAC N-Series', NOW(), NOW()),
   ('MN-505-OP', 'Freightliner EconicSD', NOW(), NOW()), ('QR-515-ST', 'Kenworth K200', NOW(), NOW()), ('UV-525-WX', 'Peterbilt 320', NOW(), NOW()),
   ('YZ-535-AB', 'Mack LR', NOW(), NOW()), ('CD-545-EF', 'Western Star 57X', NOW(), NOW()), ('GH-555-IJ', 'International MV', NOW(), NOW()),
   ('KL-565-MN', 'Volvo FE', NOW(), NOW());

   -- 50 DRIVERS
   INSERT INTO drivers (driver_id, driver_name, phone_number, license_number, created_at, updated_at) VALUES
   (gen_random_uuid(), 'John Smith', '555-0101', 'D1111111', NOW(), NOW()), (gen_random_uuid(), 'Maria Garcia', '555-0102', 'D2222222', NOW(), NOW()),
   (gen_random_uuid(), 'David Johnson', '555-0103', 'D3333333', NOW(), NOW()), (gen_random_uuid(), 'Li Wei', '555-0104', 'D4444444', NOW(), NOW()),
   (gen_random_uuid(), 'Fatima Ahmed', '555-0105', 'D5555555', NOW(), NOW()), (gen_random_uuid(), 'Ivan Petrov', '555-0106', 'D6666666', NOW(), NOW()),
   (gen_random_uuid(), 'Yuki Tanaka', '555-0107', 'D7777777', NOW(), NOW()), (gen_random_uuid(), 'Sofia Rossi', '555-0108', 'D8888888', NOW(), NOW()),
   (gen_random_uuid(), 'Carlos Hernandez', '555-0109', 'D9999999', NOW(), NOW()), (gen_random_uuid(), 'Anya Sharma', '555-0110', 'D1010101', NOW(), NOW()),
   (gen_random_uuid(), 'Jan Kowalski', '555-0111', 'D1212121', NOW(), NOW()), (gen_random_uuid(), 'Olivia Williams', '555-0112', 'D1313131', NOW(), NOW()),
   (gen_random_uuid(), 'Mohammed Ali', '555-0113', 'D1414141', NOW(), NOW()), (gen_random_uuid(), 'Emma Brown', '555-0114', 'D1515151', NOW(), NOW()),
   (gen_random_uuid(), 'Hans Müller', '555-0115', 'D1616161', NOW(), NOW()), (gen_random_uuid(), 'Chloe Dubois', '555-0116', 'D1717171', NOW(), NOW()),
   (gen_random_uuid(), 'Kenji Suzuki', '555-0117', 'D1818181', NOW(), NOW()), (gen_random_uuid(), 'Isabella Costa', '555-0118', 'D1919191', NOW(), NOW()),
   (gen_random_uuid(), 'Liam Wilson', '555-0119', 'D2020202', NOW(), NOW()), (gen_random_uuid(), 'Zoe Papadopoulos', '555-0120', 'D2121212', NOW(), NOW()),
   (gen_random_uuid(), 'Alexey Ivanov', '555-0121', 'D2323232', NOW(), NOW()), (gen_random_uuid(), 'Mia Jones', '555-0122', 'D2424242', NOW(), NOW()),
   (gen_random_uuid(), 'Chen Yue', '555-0123', 'D2525252', NOW(), NOW()), (gen_random_uuid(), 'Amir Khan', '555-0124', 'D2626262', NOW(), NOW()),
   (gen_random_uuid(), 'Grace Taylor', '555-0125', 'D2727272', NOW(), NOW()), (gen_random_uuid(), 'Lars Andersen', '555-0126', 'D2828282', NOW(), NOW()),
   (gen_random_uuid(), 'Kim Min-jun', '555-0127', 'D2929292', NOW(), NOW()), (gen_random_uuid(), 'Eva Novak', '555-0128', 'D3030303', NOW(), NOW()),
   (gen_random_uuid(), 'Daniel Martinez', '555-0129', 'D3131313', NOW(), NOW()), (gen_random_uuid(), 'Sara Johansson', '555-0130', 'D3232323', NOW(), NOW()),
   (gen_random_uuid(), 'Lucas da Silva', '555-0131', 'D3434343', NOW(), NOW()), (gen_random_uuid(), 'Alice Miller', '555-0132', 'D3535353', NOW(), NOW()),
   (gen_random_uuid(), 'Mustafa Yilmaz', '555-0133', 'D3636363', NOW(), NOW()), (gen_random_uuid(), 'Ava Smith', '555-0134', 'D3737373', NOW(), NOW()),
   (gen_random_uuid(), 'Tariq Al-Farsi', '555-0135', 'D3838383', NOW(), NOW()), (gen_random_uuid(), 'Nina Van der Berg', '555-0136', 'D3939393', NOW(), NOW()),
   (gen_random_uuid(), 'Oscar Romero', '555-0137', 'D4040404', NOW(), NOW()), (gen_random_uuid(), 'Fatima Zahra', '555-0138', 'D4141414', NOW(), NOW()),
   (gen_random_uuid(), 'Benjamin Moore', '555-0139', 'D4242424', NOW(), NOW()), (gen_random_uuid(), 'Anna Ivanova', '555-0140', 'D4343434', NOW(), NOW()),
   (gen_random_uuid(), 'Gabriel Rousseau', '555-0141', 'D4545454', NOW(), NOW()), (gen_random_uuid(), 'Emily White', '555-0142', 'D4646464', NOW(), NOW()),
   (gen_random_uuid(), 'Ibrahim Hassan', '555-0143', 'D4747474', NOW(), NOW()), (gen_random_uuid(), 'Charlotte Lee', '555-0144', 'D4848484', NOW(), NOW()),
   (gen_random_uuid(), 'Anton Svensson', '555-0145', 'D4949494', NOW(), NOW()), (gen_random_uuid(), 'Zainab Abbasi', '555-0146', 'D5050505', NOW(), NOW()),
   (gen_random_uuid(), 'Ethan Clark', '555-0147', 'D5151515', NOW(), NOW()), (gen_random_uuid(), 'Julia Popescu', '555-0148', 'D5252525', NOW(), NOW()),
   (gen_random_uuid(), 'Mateo Vargas', '555-0149', 'D5353535', NOW(), NOW()), (gen_random_uuid(), 'Elif Aslan', '555-0150', 'D5454545', NOW(), NOW());

